# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='hours',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hours',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
