# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20170912_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hours',
            new_name='HoursLocation',
        ),
    ]
