# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_auto_20170912_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslocation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
