# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0005_auto_20170912_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslocation',
            name='my_date_field',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
