# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0006_hourslocation_my_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourslocation',
            old_name='name',
            new_name='ChildsName',
        ),
        migrations.AddField(
            model_name='hourslocation',
            name='OpportunityNumber',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
