# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0008_auto_20170912_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourslocation',
            old_name='name',
            new_name='ChildsName',
        ),
    ]
