# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0009_auto_20170912_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
